// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GodotVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "GodotVSIX.986e5a95-da3b-42e3-87c5-e5b4b7a3a850";
        public const string Name = "GodotVSIX";
        public const string Description = @"Godot Visual Studio Support";
        public const string Language = "zh-CN";
        public const string Version = "1.0";
        public const string Author = "BackPool-MD";
        public const string Tags = "";
    }
}
