// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GodotVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GodotVSIXString = "9e97ee61-2580-44e5-8b54-e59535368662";
        public static Guid GodotVSIX = new Guid(GodotVSIXString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GodotMenu = 0x1021;
        public const int MyMenuGroup = 0x0001;
        public const int UTF8Command = 0x0100;
        public const int AndroidBuid = 0x0101;
    }
}